name: Exploring workflow dispatch

on:

 push

jobs:
  first_jobname:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        run: echo "My first Github Actions Job"

      - name: List files
        run: ls

      - name: Read file
        run: date
